baseURL = 'https://www.cp-dev.tech/'
languageCode = 'en-us'
title = 'CP-DEV'
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentsCodeFences = true
enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  homeTitle = "CP-DEV" # Set a different text for the header on the home page
  subtitle = "Chase Percy"
  mainSections = ["post"]
  logo = "/img/snake.webp" # Expecting square dimensions
  favicon = "/img/s_favicon.webp"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  readingTime = false
  showRelatedPosts = true
  hideAuthor = true
  selfHosted = true

[Author]
  name = "Chase Percy"
  website = ""
  email = "chase@cp-dev.tech"
  github = "Chase-Percy"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "info/about/"
    weight = 4

[[menu.main]]
    identifier = "Projects"
    name = "Projects"
    weight = 2

[[menu.main]]
    parent = "Projects"
    name = "Big Balls Roll"
    url = "project/big-balls-roll"
    weight = 1

[[menu.main]]
    parent = "Projects"
    name = "The Arcanist"
    url = "project/the-arcanist"
    weight = 2

[[menu.main]]
    parent = "Projects"
    name = "Unix Shell"
    url = "project/unix-shell"
    weight = 3

[[menu.main]]
    parent = "Projects"
    identifier = "Algorithms"
    url = "project/algorithms"
    name = "Algorithms"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "info/contact-details"
    weight = 5

[[Params.bigimg]]
  src = "/img/trees.jpg" # image credit: https://www.pexels.com/photo/pine-trees-1834399/
