[[plugins]]
package = "netlify-plugin-image-optim"


# Config for the Netlify Build Plugin: netlify-plugin-minify-html
[[plugins]]
  package = "netlify-plugin-minify-html"

  # Specify which deploy contexts we'll minify HTML in.
  # Supports any Deploy Contexts available in Netlify.
  # https://docs.netlify.com/site-deploys/overview/#deploy-contexts
  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]

  # Optionally, override the default options for the minification
  # https://github.com/kangax/html-minifier#options-quick-reference
  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseWhiteSpace = true
    collapseInlineTagWhitespace = true
    removeRedundantAttributes = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
                                       default-src 'self';

                                       font-src 'self'
                                       https://cdnjs.cloudflare.com
                                       https://fonts.gstatic.com
                                       https://maxcdn.bootstrapcdn.com
                                       https://use.fontawesome.com
                                       https://stackpath.bootstrapcdn.com;

                                       img-src 'self'
                                       https://i.ytimg.com/vi_webp/2XUEb0cKoXo/mqdefault.webp
                                       https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.2/default-skin/default-skin.svg
                                       https://d33wubrfki0l68.cloudfront.net;

                                       frame-src 'self'
                                       https://www.youtube.com/;

                                       object-src 'none';

                                       style-src 'self'
                                       https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css
                                       https://use.fontawesome.com/releases/v5.5.0/css/all.css
                                       https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css
                                       https://fonts.googleapis.com
                                       https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.2/photoswipe.min.css
                                       https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.2/default-skin/default-skin.min.css
                                       'sha256-slTiuoOyHa8PK+bmv7Jn6MimHl8/v+xwARlD0sj/zfA='
                                       'sha256-SDcE9vKARLw3IvI2Yj1CWCkfl8YONU0VM/QOKxFek5c='
                                       'sha256-UBCHLCqruOsRKPsCwz1OvHuxPBeEvdFH9piYgDdpw28='
                                       'sha256-TticbkVH4dhw94fpOkML+S3qamZBFFoEaSsxCkTy7EE='
                                       'sha256-PDPmXZiYkV0/hkF3A8lI7Sb1Yss6r0SytdtPe6DC5PM='
                                       'sha256-peN89MK9iAymBz+6LNPYjp9ZwGTR3MtqIaBAfuckquI='
                                       'sha256-NPY5CJj9epSon2pbrw7eMFxO8tJT8/CkmVZ4PgDSdvw='
                                       'sha256-cgdsZAF6T6ZzaK0C16FZ4OSYGdapU2km5/SUcwOHO/Y='
                                       'sha256-ZXk3zFkN2Ntejzq+inSyPI8X1iEjaHc2USTOom56DyQ='
                                       'sha256-nNjO4vaA7lRpu1i489DcQ3sHp9efSP+b13buVe0S1OY='
                                       'sha256-VVdhf4mhGN/LViHGX4wTZ0xHElnOYgT3ITSKo2d70qk='
                                       'sha256-+y9gMGV/P3FngGum9Mvnx6eIkNXd3OdDL9QocAU07Ag='
                                       'sha256-GAKmQIFmKEndinx2ia5tcieIbmUHMFahxx/NeF/qaao='
                                       'sha256-NGmS0KnoFDIlsdtZdtOPR52L8m75ZJNNhwPjkNjcCmw=';

                                       script-src 'self'
                                       https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.js
                                       https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/contrib/auto-render.min.js
                                       https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js
                                       https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js
                                       https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.js
                                       https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe-ui-default.min.js
                                       https://cdn.babylonjs.com/babylon.js
                                       https://cdn.babylonjs.com/loaders/babylonjs.loaders.min.js
                                       https://code.jquery.com/pep/0.4.3/pep.js
                                       https://d33wubrfki0l68.cloudfront.net
                                       'sha256-GKAN6QbhGHqa8VmVzy/zBId270+p8iMUhTPpbJQlRT4='
                                       'sha256-0PsWxn+B8H5lwgiessadGq3VFchRU+6mjyWpvUG5Ce8='
                                       'sha256-qs0Yszad4nwVEsj8rSanks1hcT2dyXhaY9lTOibYQLU='; '''
