[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; plugin-types 'self'; sandbox 'self'; report-uri https://csp.4armed.io/report; img-src http://localhost:1313; script-src-elem http://localhost:1313 https://code.jquery.com:443 https://cdnjs.cloudflare.com:443 https://cdn.jsdelivr.net:443 https://cdn.babylonjs.com:443; style-src-elem https://use.fontawesome.com:443 https://cdnjs.cloudflare.com:443 https://maxcdn.bootstrapcdn.com:443 http://localhost:1313 https://fonts.googleapis.com:443; frame-src https://www.youtube.com:443;"
