[build]
  command = "hugo --minify"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
                                       default-src 'self'
                                       https://elegant-pasteur-9ecd6b.netlify.app;

                                       font-src 'self'
                                       https://elegant-pasteur-9ecd6b.netlify.app;

                                       img-src 'self'
                                       https://elegant-pasteur-9ecd6b.netlify.app
                                       https://i.ytimg.com/vi_webp/2XUEb0cKoXo/mqdefault.webp
                                       https://d33wubrfki0l68.cloudfront.net;

                                       frame-src 'self'
                                       https://www.youtube.com/;

                                       object-src 'none';

                                       style-src 'self'
                                       https://elegant-pasteur-9ecd6b.netlify.app
                                       'sha256-slTiuoOyHa8PK+bmv7Jn6MimHl8/v+xwARlD0sj/zfA='
                                       'sha256-SDcE9vKARLw3IvI2Yj1CWCkfl8YONU0VM/QOKxFek5c='
                                       'sha256-UBCHLCqruOsRKPsCwz1OvHuxPBeEvdFH9piYgDdpw28='
                                       'sha256-TticbkVH4dhw94fpOkML+S3qamZBFFoEaSsxCkTy7EE='
                                       'sha256-PDPmXZiYkV0/hkF3A8lI7Sb1Yss6r0SytdtPe6DC5PM='
                                       'sha256-peN89MK9iAymBz+6LNPYjp9ZwGTR3MtqIaBAfuckquI='
                                       'sha256-NPY5CJj9epSon2pbrw7eMFxO8tJT8/CkmVZ4PgDSdvw='
                                       'sha256-cgdsZAF6T6ZzaK0C16FZ4OSYGdapU2km5/SUcwOHO/Y='
                                       'sha256-faF1ECocvHGtuKtNjtyYZSBZjz5LYZ36UQdMg5UAaKc='
                                       'sha256-H6WnXlal+Rl5E9mjv3zTHGqpQG1J0j5tJ+zGCcyuA5Q='
                                       'sha256-nHO1EqgalDviFCEOicxRbTu95Emla6SI0pkw+NHeuPE='
                                       'sha256-DuBbm8hhpvismraz3MJhBlMD6Gh0LrHHYSn/P7dZLg0='
                                       'sha256-j/wQfv+LDnGZd6+340jjpwCuaN4MphLC5X0dVKcwpKs='
                                       'sha256-1W85jEjWZNk1NOUKfq9C8k3V12XMU7Qc5cIRSJar0gc='
                                       'sha256-OJSHKOjjFoWqGO7bP0otblj28VVjR5xVY5Vm4tv76A0=';

                                       script-src 'self'
                                       https://elegant-pasteur-9ecd6b.netlify.app
                                       https://cdn.babylonjs.com/babylon.js
                                       https://cdn.babylonjs.com/loaders/babylonjs.loaders.min.js
                                       https://code.jquery.com/pep/0.4.3/pep.js
                                       https://d33wubrfki0l68.cloudfront.net
                                       'sha256-GKAN6QbhGHqa8VmVzy/zBId270+p8iMUhTPpbJQlRT4='
                                       'sha256-0PsWxn+B8H5lwgiessadGq3VFchRU+6mjyWpvUG5Ce8='
                                       'sha256-qs0Yszad4nwVEsj8rSanks1hcT2dyXhaY9lTOibYQLU='
                                       'sha256-V42Y1nx2Vbr1877xzmCTt5qllEyRJjtdyGloSxQwx34='; '''
